# This should be filled out and placed in /cu-blogs/config/database.yml
# This file is *only* used to generate wp-config.php
encryption_key:
email:
  username: 
  password: 
roleservice:
  api_url:
  username:
  password: